#!/usr/bin/env node
/**
 * gen-config.mjs — generate the LiteLLM config.yaml from live Ollama rosters.
 *
 * Minimal by design (docs/design/add-litellm.md): model_list only — one
 * ollama_chat deployment per (host, tag), shared model_name across hosts for
 * load balancing, streaming-safe agentic timeouts. No routing/classifier
 * coupling — dependent skills import generate() and post-process.
 *
 * Keyless v1: no master_key, no DATABASE_URL.
 *
 * Usage:
 *   node gen-config.mjs [--hosts http://localhost:11434,http://10.0.0.5:11434]
 *                       [--tags-file fixtures/ollama-tags.json]  (offline/test)
 *                       [--out config.yaml]
 *
 * With --tags-file, no network calls are made; the file maps host → /api/tags
 * response, letting tests and no-Ollama environments run the generator.
 */
import { readFileSync, writeFileSync } from 'node:fs';

const args = process.argv.slice(2);
const opt = (name, dflt) => {
  const i = args.indexOf(`--${name}`);
  return i >= 0 && args[i + 1] ? args[i + 1] : dflt;
};

const HOSTS = opt('hosts', process.env.OLLAMA_HOSTS ?? 'http://localhost:11434')
  .split(',')
  .map((h) => h.trim().replace(/\/$/, ''))
  .filter(Boolean);
const TAGS_FILE = opt('tags-file', null);
const OUT = opt('out', null);

/** Fetch /api/tags for a host, or read from the fixture map in --tags-file. */
async function tagsFor(host, fixtures) {
  if (fixtures) {
    const entry = fixtures[host];
    if (!entry) throw new Error(`--tags-file has no entry for host ${host}`);
    return entry;
  }
  const res = await fetch(`${host}/api/tags`, { signal: AbortSignal.timeout(5000) });
  if (!res.ok) throw new Error(`GET ${host}/api/tags → HTTP ${res.status}`);
  return res.json();
}

/**
 * A container-reachable api_base for a host. Ollama on the host's localhost
 * must be addressed as host.docker.internal from inside the LiteLLM container;
 * LAN/Tailscale hosts pass through unchanged.
 */
function containerReachable(host) {
  return host.replace(/^(https?:\/\/)(localhost|127\.0\.0\.1)(?=[:/]|$)/, '$1host.docker.internal');
}

function yamlEscape(s) {
  return /[:#{}[\],&*?|<>=!%@`"']/.test(s) ? JSON.stringify(s) : s;
}

export async function generate({ hosts = HOSTS, fixtures = null } = {}) {
  const modelList = [];
  for (const host of hosts) {
    const tags = await tagsFor(host, fixtures);
    for (const m of tags.models ?? []) {
      // model_name is the tag itself; the same tag on several hosts becomes
      // multiple deployments under one name — exactly how LiteLLM
      // load-balances, so the reuse is deliberate.
      modelList.push({
        model_name: m.name,
        litellm_params: {
          model: `ollama_chat/${m.name}`,
          api_base: containerReachable(host),
        },
      });
    }
  }
  if (modelList.length === 0) throw new Error('no models discovered on any host');

  const lines = [];
  lines.push('# Generated by add-litellm/gen-config.mjs — regenerate, do not hand-edit.');
  lines.push(`# hosts: ${hosts.join(', ')}`);
  lines.push('model_list:');
  for (const m of modelList) {
    lines.push(`  - model_name: ${yamlEscape(m.model_name)}`);
    lines.push('    litellm_params:');
    lines.push(`      model: ${yamlEscape(m.litellm_params.model)}`);
    lines.push(`      api_base: ${yamlEscape(m.litellm_params.api_base)}`);
  }
  lines.push('');
  lines.push('litellm_settings:');
  lines.push('  # Agentic turns are long — generous end-to-end timeout.');
  lines.push('  request_timeout: 600');
  lines.push('  num_retries: 2');
  lines.push('  drop_params: true');
  lines.push('');
  lines.push('router_settings:');
  lines.push('  routing_strategy: simple-shuffle');
  lines.push('');
  lines.push('# Keyless v1 (docs/design/add-litellm.md): no master_key, no DATABASE_URL.');
  lines.push('# The installer binds the proxy to localhost + the docker bridge — never public.');
  return lines.join('\n') + '\n';
}

// CLI entry
if (import.meta.url === `file://${process.argv[1]}`) {
  const fixtures = TAGS_FILE ? JSON.parse(readFileSync(TAGS_FILE, 'utf8')) : null;
  const yaml = await generate({ hosts: HOSTS, fixtures });
  if (OUT) {
    writeFileSync(OUT, yaml);
    console.error(`wrote ${OUT}`);
  } else {
    process.stdout.write(yaml);
  }
}
